version: '3.1'
services:
    cassandra:
        image: bitnami/cassandra
        container_name: cassandra-binami
        ports: 
            - 9042:9042
            - 7000:7000
            - 7199:7199
        environment:
            - CASSANDRA_USER=cassandra
            - CASSANDRA_PASSWORD=cassandra
            - CASSANDRA_TRANSPORT_PORT_NUMBER=7000